EvoComputerTechService/Areas/Admin/Controllers/OperatorController.cs
using EvoComputerTechService.Data;
using EvoComputerTechService.Extensions;
using EvoComputerTechService.Models;
using EvoComputerTechService.Models.Entities;
using EvoComputerTechService.Models.Identity;
using EvoComputerTechService.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EvoComputerTechService.Areas.Admin.Controllers
{
    public class OperatorController : OperatorBaseController
    {
        private readonly MyContext _dbContext;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IEmailSender _emailSender;

        public OperatorController(MyContext dbContext, UserManager<ApplicationUser> userManager,IEmailSender emailSender)
        {
            _dbContext = dbContext;
            _userManager = userManager;
            _emailSender = emailSender;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult WaitingIssues()
        {
            var waitingIssues = _dbContext.Issues.Where(x=>x.IssueState == IssueStates.Beklemede).ToList();

            return View(waitingIssues);
        }

        [HttpGet]
        public   IActionResult ActiveIssues()
        {
            var activeIssues = _dbContext.Issues.Where(x => x.IssueState == IssueStates.Islemde).ToList();

            return View(activeIssues);
        }

        [HttpGet]
        public IActionResult AssignedIssues()
        {
            var assignedIssues = _dbContext.Issues.Where(x => x.IssueState == IssueStates.Atandi).ToList();

            return View(assignedIssues);
        }

        [HttpGet]
        public IActionResult CompletedIssues()
        {
            var completedIssues = _dbContext.Issues.Where(x => x.IssueState == IssueStates.Tamamlandi).ToList();

            return View(completedIssues);
        }

        [HttpGet]
        public IActionResult AssignTechnician(Guid id)
        {
            var issue = _dbContext.Issues.Find(id);

            var Technicians = new List<SelectListItem>();

            var x = _userManager.GetUsersInRoleAsync("Technician").Result;
            var users = x.OfType<ApplicationUser>();

            foreach (var item in users)
            {
                Technicians.Add(new SelectListItem
                {
                    Text = $"{item.Name} {item.Surname}",
                    Value = item.Id.ToString()
                });
            }

            ViewBag.Technicians = Technicians;
            
            return View(issue);
        }

        [HttpPost]
        public async Task<IActionResult> AssignTechnician(string[] Technician,Guid id)
        {
            //if (Technician.Length>1)
            //{
                 
            //}

            var issue = _dbContext.Issues.Find(id);
            issue.TechnicianId = Technician[0];
            issue.IssueState = IssueStates.Atandi;

            var user=await _userManager.FindByIdAsync(issue.TechnicianId);

            _dbContext.SaveChanges();

            await _emailSender.SendAsync(new EmailMessage()
            {
                //User maili koy
                Contacts = new string[] { "abc@gmail.com" },
                Body = $"{HttpContext.User.Identity.Name} Adlı Kullanıcı  Tarafından" +
                $" {issue.IssueName} Adlı Arıza {user.Name} Atandı",
                Subject = "Teknik Arıza Kaydı",
                Cc = new string[] { "abc@gmail.com" },
                Bcc = new string[] { },
            });

            return RedirectToAction("AssignedIssues");
        }



    }
}

EvoComputerTechService/Controllers/IssueController.cs
using AutoMapper;
using EvoComputerTechService.Data;
using EvoComputerTechService.Extensions;
using EvoComputerTechService.Models.Entities;
using EvoComputerTechService.Models.Identity;
using EvoComputerTechService.Services;
using EvoComputerTechService.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EvoComputerTechService.Controllers
{
    [Authorize]
    public class IssueController : Controller
    {
        private readonly MyContext _dbContext;
        private readonly UserManager<ApplicationUser> _userManager;

        public IssueController(MyContext dbContext, UserManager<ApplicationUser> userManager)
        {
            _dbContext = dbContext;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> GetIssues()
        {
            var user = await _userManager.FindByIdAsync(HttpContext.GetUserId());
            var issues = _dbContext.Issues.Where(x=>x.UserId == user.Id).ToList();

           // var issues=_dbContext.Issues.Where(x=>x.UserId==user.Id && x.IssueState==IssueStates.Tamamlandi).ToList();

            return View(issues);
        }

        [HttpGet]
        public IActionResult CreateIssue()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> CreateIssue(string lat,string lng,Issue model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await _userManager.FindByIdAsync(HttpContext.GetUserId());
            if(user == null)
            {

            }

            var issue = new Issue()
            {
                IssueName = model.IssueName,
                Description = model.Description,
                AddressDetail = model.AddressDetail,
                UserId = user.Id,
                IssueState = IssueStates.Beklemede,
                CreatedDate = DateTime.Now,
                CreatedUser = user.Id,
                Latitude = lat,
                Longitude = lng
            };

            _dbContext.Issues.Add(issue);
            _dbContext.SaveChanges();


            return View(model);
        }

        [HttpGet]
        public IActionResult UpdateIssue(Guid id)
        {
            var issue = _dbContext.Issues.Find(id);
            if(issue == null)
            {

            }

            return View(issue);
        }

        [HttpPost]
        public IActionResult UpdateIssue(string lat, string lng, Issue model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            Issue issue = _dbContext.Issues.Find(model.Id);
            issue.IssueName = model.IssueName;
            issue.Description = model.Description;
            issue.AddressDetail = model.AddressDetail;
            issue.UpdatedDate = DateTime.Now;
            issue.Latitude = lat;
            issue.Longitude = lng;

            _dbContext.SaveChanges();
            return RedirectToAction("GetIssues");
        }
        public IActionResult DeleteIssue(Guid id)
        {
            var issue = _dbContext.Issues.Find(id);
            if (issue == null)
            {

            }
            _dbContext.Remove(issue);
            _dbContext.SaveChanges();

            return RedirectToAction("GetIssues");
        }
        public IActionResult CompletedIssues() 
        {
         //   var issue=_dbContext.Issues.FindAsync(id); 
           // var user = await _userManager.FindByIdAsync(HttpContext.GetUserId());

            //var completedIssues=_dbContext.Issues.Where(x=>x.Id==id && x.UserId==user.Id && x.IssueState == IssueStates.OdemeTamamlandı).ToList();

           var completedIssues=_dbContext.Issues.Where(x=>x.IssueState == IssueStates.OdemeTamamlandı).ToList();

            return View(completedIssues);
        }

     
    }
}

EvoComputerTechService/Areas/Admin/Views/Operator/ActiveIssues.cshtml
@model List<Issue>

@{
    ViewBag.Title = "İşlemde Olan Arızalar";
}

<section class="blog_area sec_pad">
    <div class="container">
        <div class="row" id="blog_masonry">
            @foreach (var item in Model)
            {
                <div class="col-lg-4 col-sm-6">
                    <div class="blog_grid_item mb-30">
                        @*<div class="blog_img">
                                <img src="~/img/blog-grid/masonry_02.jpg" alt="">
                            </div>*@
                        <div class="blog_content">
                            <div class="entry_post_info">
                                <a href="#">@item.IssueState</a>
                                <a href="#">@item.CreatedDate</a>
                            </div>
                            <a asp-controller="Issue" asp-action="UpdateIssue" asp-route-id="@item.Id">
                                <h5 class="f_p f_size_20 f_500 t_color mb_20">@item.IssueName</h5>
                            </a>
                            <p class="f_400 mb-0">
                                @item.Description
                            </p>
                            <br />
                            <div>
                                <button class="btn btn-danger">
                                    <a asp-controller="Issue" asp-action="DeleteIssue" asp-route-id="@item.Id">
                                        SİL
                                    </a>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

EvoComputerTechService/Areas/Admin/Views/Operator/AssignTechnician.cshtml
@model Issue

<form asp-area="Admin" asp-controller="Operator" asp-action="AssignTechnician" method="post">
    <input type="hidden" id="id" name="id" value="@Model.Id"/>
    <div class="form-group">
        <label>DropdownList Multiple Select</label>
        <label id="employees">
            <span style="padding-right: 10px">Hepsini Seç / Temizle </span>
            <input type="checkbox" id="hepsiniSec"><i></i>
        </label>
        <select name="Technician[]"
                id="select2"
                multiple="multiple"
                class="form-control"
                asp-items="ViewBag.Technicians">
                
         </select>
    </div>
    <div class="form-group">
       @* @if ((int)@Model.Technician>1)
         {*@
       <button type="button" class="btn btn-secondary" data-container="body" data-toggle="popover" data-placement="top" data-content="Vivamus sagittis lacus vel augue laoreet rutrum faucibus.">
  Popover on top
</button>
        }
        <button class="btn btn-primary">Ata</button>
    </div>
</form>

@section Styles
{
    <style>
        #employees {
            padding: 0 20px
        }

            #employees:last-child {
                border-bottom: 1px solid #BBB;
            }

            #employees > input {
                display: none;
            }

            #employees i {
                display: inline-block;
                float: right;
                padding: 2px;
                width: 40px;
                height: 20px;
                border-radius: 13px;
                vertical-align: middle;
                -webkit-transition: .25s .09s;
                transition: .25s .09s;
                position: relative;
                background: #d8d9db;
                box-sizing: initial;
            }

                #employees i:after {
                    content: " ";
                    display: block;
                    width: 20px;
                    height: 20px;
                    border-radius: 50%;
                    background: #fff;
                    position: absolute;
                    left: 2px;
                    -webkit-transition: .25s;
                    transition: .25s;
                }

            #employees > input:checked + i {
                background: #4bd865;
            }

                #employees > input:checked + i:after {
                    -webkit-transform: translateX(20px);
                    transform: translateX(20px);
                }

            #employees:hover {
                cursor: pointer;
            }
    </style>
}

@section Scripts
{
    
    <script>
        @*document.getElementById("id").value = @Model.Id;*@
        $(function () {
            //select2 eklentimizin tanımı
            $('#select2').select2();
            //hepsiniSec kodlarımız
            $("#hepsiniSec").on("click", function () {
                if ($(this).is(':checked')) {
                    $("#select2 > option").prop("selected", "selected");
                    $("#select2").trigger("change");
                }
                else {
                    $("#select2 > option").removeAttr("selected");
                    $("#select2").trigger("change");
                }
            });
        });
    </script>
}

EvoComputerTechService/Areas/Admin/Views/Operator/AssignedIssues.cshtml
@model List<Issue>

@{
    ViewBag.Title = "Atanmış Arızalar";
}

<section class="blog_area sec_pad">
    <div class="container">
        <div class="row" id="blog_masonry">
            @foreach (var item in Model)
            {
                <div class="col-lg-4 col-sm-6">
                    <div class="blog_grid_item mb-30">
                        @*<div class="blog_img">
                                <img src="~/img/blog-grid/masonry_02.jpg" alt="">
                            </div>*@
                        <div class="blog_content">
                            <div class="entry_post_info">
                                <a href="#">@item.IssueState</a>
                                <a href="#">@item.CreatedDate</a>
                            </div>
                            <a asp-controller="Issue" asp-action="UpdateIssue" asp-route-id="@item.Id">
                                <h5 class="f_p f_size_20 f_500 t_color mb_20">@item.IssueName</h5>
                            </a>
                            <p class="f_400 mb-0">
                                @item.Description
                            </p>
                            <br />
                            <div>
                                <button class="btn btn-danger">
                                    <a asp-controller="Issue" asp-action="DeleteIssue" asp-route-id="@item.Id">
                                        SİL
                                    </a>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

EvoComputerTechService/Areas/Admin/Views/Operator/CompletedIssues.cshtml
@model List<Issue>

@{
    ViewBag.Title = "Tamamlanan Arızalar";
}

<section class="blog_area sec_pad">
    <div class="container">
        <div class="row" id="blog_masonry">
            @foreach (var item in Model)
            {
                <div class="col-lg-4 col-sm-6">
                    <div class="blog_grid_item mb-30">
                        @*<div class="blog_img">
                                <img src="~/img/blog-grid/masonry_02.jpg" alt="">
                            </div>*@
                        <div class="blog_content">
                            <div class="entry_post_info">
                                <a href="#">@item.IssueState</a>
                                <a href="#">@item.CreatedDate</a>
                            </div>
                            <a asp-controller="Issue" asp-action="UpdateIssue" asp-route-id="@item.Id">
                                <h5 class="f_p f_size_20 f_500 t_color mb_20">@item.IssueName</h5>
                            </a>
                            <p class="f_400 mb-0">
                                @item.Description
                            </p>
                            <br />
                            <div>
                                <button class="btn btn-danger">
                                    <a asp-controller="Issue" asp-action="DeleteIssue" asp-route-id="@item.Id">
                                        SİL
                                    </a>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

EvoComputerTechService/Areas/Admin/Views/Operator/WaitingIssues.cshtml
@model List<Issue>

@{ 
    ViewBag.Title = "Bekleyen Arızalar";
}

<section class="blog_area sec_pad">
    <div class="container">
        <div class="row" id="blog_masonry">
            @foreach (var item in Model)
            {
                <div class="col-lg-4 col-sm-6">
                    <div class="blog_grid_item mb-30">
                        @*<div class="blog_img">
                                <img src="~/img/blog-grid/masonry_02.jpg" alt="">
                            </div>*@
                        <div class="blog_content">
                            <div class="entry_post_info">
                                <a href="#">@item.IssueState</a>
                                <a href="#">@item.CreatedDate</a>
                            </div>
                            <a asp-controller="Issue" asp-action="UpdateIssue" asp-route-id="@item.Id">
                                <h5 class="f_p f_size_20 f_500 t_color mb_20">@item.IssueName</h5>
                            </a>
                            <p class="f_400 mb-0">
                                @item.Description
                            </p>
                            <br />
                            <div>
                                <button class="btn btn-danger">
                                    <a asp-area="Admin" asp-controller="Operator" asp-action="AssignTechnician" asp-route-id="@item.Id">
                                        TEKNİSYEN ATA
                                    </a>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>