EvoComputerTechService/Areas/Admin/Controllers/TechnicianController.cs
using EvoComputerTechService.Data;
using EvoComputerTechService.Extensions;
using EvoComputerTechService.Models;
using EvoComputerTechService.Models.Entities;
using EvoComputerTechService.Models.Identity;
using EvoComputerTechService.Services;
using EvoComputerTechService.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EvoComputerTechService.Areas.Admin.Controllers
{
    public class TechnicianController : TechnicianBaseController
    {
        private readonly MyContext _dbContext;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IEmailSender _emailSender;


        public TechnicianController(MyContext dbContext, UserManager<ApplicationUser> userManager,IEmailSender emailSender)
        {
            _dbContext = dbContext;
            _userManager = userManager;
            _emailSender = emailSender;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> MyIssues()
        {
            var user = await _userManager.FindByIdAsync(HttpContext.GetUserId());

            var myIssues = _dbContext.Issues.Where(x => x.TechnicianId == user.Id && x.IssueState == IssueStates.Atandi).ToList();

            return View(myIssues);
        }
        public IActionResult AcceptIssue(Guid id)
        {
            var issue = _dbContext.Issues.Find(id);
            issue.IssueState = IssueStates.Islemde;
            _dbContext.SaveChanges();

            return RedirectToAction("AcceptedIssues");
        }

        [HttpGet]
        public async Task<IActionResult> AcceptedIssues()
        {
            var user = await _userManager.FindByIdAsync(HttpContext.GetUserId());

            var acceptedIssues = _dbContext.Issues.Where(x => x.TechnicianId == user.Id &&
                x.IssueState == IssueStates.Islemde)
                .ToList();

            return View(acceptedIssues);
        }

        [HttpGet]
        public IActionResult IssueDetail(Guid id)
        {
          TempData["issueId"] = id;
          var issue = _dbContext.Issues.Find(id);
          var products=_dbContext.Products.ToList();
          var issueInProduct=_dbContext.IssueProducts.Where(x=>x.IssueId==issue.Id).Include(x=>x.Product).ToList();
          
          IssueProductViewModel model =new IssueProductViewModel();
          model.Products=products;
          model.IssueProducts = issueInProduct;

          TempData["buttonCheck"] = (int)issue.IssueState as object;

          return View(model);
          
        }
        [HttpPost]
        public IActionResult AddProduct(Guid id) 
        {
            var issueId = TempData["issueId"];

            var issue = _dbContext.Issues.Find(issueId);
            var product = _dbContext.Products.Find(id);

            var issueinProduct = _dbContext.IssueProducts.Where(x => x.IssueId == issue.Id).Include(x => x.Product).ToList();

            var control=issueinProduct.SingleOrDefault(x=>x.ProductId==product.Id);

            if (control==null)
            {
                IssueProducts model = new IssueProducts()
                {
                    Issue = issue,
                    Product = product,
                    ProductId = product.Id,
                    IssueId = issue.Id,
                    Price = product.Price,
                    Quantity = 1
                };
                 _dbContext.IssueProducts.Add(model);
            }
            else
            {
                control.Quantity++;
                control.Price= product.Price*control.Quantity;
            }

            _dbContext.SaveChanges();

            return RedirectToAction("IssueDetail", new { id = issueId });
        }
        [HttpPost]
        public  IActionResult DeleteProduct(Guid id) 
        {
            var product = _dbContext.Products.Find(id);
            var issueInProduct = _dbContext.IssueProducts.Where(x => x.ProductId == product.Id).FirstOrDefault();

            _dbContext.Remove(issueInProduct);
            _dbContext.SaveChanges();

            return RedirectToAction("IssueDetail", new { id = issueInProduct.IssueId }); 
        }
        public async Task<IActionResult> CompletedIssues()
        {
            // TempData["issueId"] = id;
             var issueId = TempData["issueId"];
            // var issue = _dbContext.Issues.Find(issueId);
            var issue = _dbContext.Issues.Find(issueId);
            issue.IssueState = IssueStates.Tamamlandi;
            _dbContext.SaveChanges();

            var user = await _userManager.FindByIdAsync(issue.UserId);

            //string link = HttpContext.Request.Url.Scheme + "://" + HttpContext.Request.Url.Authority + Url.Action("ResetPassword", "Account", new { key = randomString });
           // string url = this.Url.Action("Purchase", "Payment");
            await _emailSender.SendAsync(new EmailMessage()
            {
                //User maili koy
                Contacts = new string[] { "abc@gmail.com" },
                Body = $" {user.Name} Tarafından Olusturulan  {issue.IssueName} Adlı Arıza {HttpContext.User.Identity.Name} Tarafından  Tamamlandı Lutfen Odeme yapınız <br/> " + 
                $"Please make your payment by  < a href='https://localhost:44343/Payment/Purchase'> clicking here </ a >",
               
                // to do : URL LINKI CALISILACAK

               // // https://localhost:44343/admin/Technician/MyIssues
               //// < a href = 'https://localhost:44343/Payment/Purchase' > clicking here </ a >.
                Subject = " Odeme BEKLEME",
                Cc = new string[] { "abc@gmail.com" },
                Bcc = new string[] { },
            });

            return RedirectToAction("CompletedIssuesDone",new { id=issue.Id});
        }
        public async Task<IActionResult> CompletedIssuesDone()
        {
            var user = await _userManager.FindByIdAsync(HttpContext.GetUserId());

            //var completedIssues = _dbContext.Issues.Where(x => x.TechnicianId == user.Id && x.IssueState == IssueStates.Tamamlandi).ToList();

            var  completedIssues=_dbContext.Issues.Where(x=>x.TechnicianId==user.Id && (int)x.IssueState>=3).ToList();

            return View(completedIssues);
        }

    }

}

EvoComputerTechService/Controllers/IssueController.cs
using AutoMapper;
using EvoComputerTechService.Data;
using EvoComputerTechService.Extensions;
using EvoComputerTechService.Models.Entities;
using EvoComputerTechService.Models.Identity;
using EvoComputerTechService.Services;
using EvoComputerTechService.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EvoComputerTechService.Controllers
{
    [Authorize]
    public class IssueController : Controller
    {
        private readonly MyContext _dbContext;
        private readonly UserManager<ApplicationUser> _userManager;

        public IssueController(MyContext dbContext, UserManager<ApplicationUser> userManager)
        {
            _dbContext = dbContext;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> GetIssues()
        {
            var user = await _userManager.FindByIdAsync(HttpContext.GetUserId());
            var issues = _dbContext.Issues.Where(x=>x.UserId == user.Id).ToList();

           // var issues=_dbContext.Issues.Where(x=>x.UserId==user.Id && x.IssueState==IssueStates.Tamamlandi).ToList();

            return View(issues);
        }

        [HttpGet]
        public IActionResult CreateIssue()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> CreateIssue(string lat,string lng,Issue model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await _userManager.FindByIdAsync(HttpContext.GetUserId());
            if(user == null)
            {

            }

            var issue = new Issue()
            {
                IssueName = model.IssueName,
                Description = model.Description,
                AddressDetail = model.AddressDetail,
                UserId = user.Id,
                IssueState = IssueStates.Beklemede,
                CreatedDate = DateTime.Now,
                CreatedUser = user.Id,
                Latitude = lat,
                Longitude = lng
            };

            _dbContext.Issues.Add(issue);
            _dbContext.SaveChanges();


            return View(model);
        }

        [HttpGet]
        public IActionResult UpdateIssue(Guid id)
        {
            var issue = _dbContext.Issues.Find(id);
            if(issue == null)
            {

            }

            return View(issue);
        }

        [HttpPost]
        public IActionResult UpdateIssue(string lat, string lng, Issue model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            Issue issue = _dbContext.Issues.Find(model.Id);
            issue.IssueName = model.IssueName;
            issue.Description = model.Description;
            issue.AddressDetail = model.AddressDetail;
            issue.UpdatedDate = DateTime.Now;
            issue.Latitude = lat;
            issue.Longitude = lng;

            _dbContext.SaveChanges();
            return RedirectToAction("GetIssues");
        }
        public IActionResult DeleteIssue(Guid id)
        {
            var issue = _dbContext.Issues.Find(id);
            if (issue == null)
            {

            }
            _dbContext.Remove(issue);
            _dbContext.SaveChanges();

            return RedirectToAction("GetIssues");
        }
        public IActionResult CompletedIssues() 
        {
         //   var issue=_dbContext.Issues.FindAsync(id); 
           // var user = await _userManager.FindByIdAsync(HttpContext.GetUserId());

            //var completedIssues=_dbContext.Issues.Where(x=>x.Id==id && x.UserId==user.Id && x.IssueState == IssueStates.OdemeTamamlandı).ToList();

           var completedIssues=_dbContext.Issues.Where(x=>x.IssueState == IssueStates.OdemeTamamlandı).ToList();

            return View(completedIssues);
        }

     
    }
}

EvoComputerTechService/Areas/Admin/Views/Technician/AcceptedIssues.cshtml
@model List<Issue>

@{
    ViewBag.Title = "Atanan Arızalar";
}

<section class="blog_area sec_pad">
    <div class="container">
        <div class="row" id="blog_masonry">
            @foreach (var item in Model)
            {
                <div class="col-lg-4 col-sm-6">
                    <div class="blog_grid_item mb-30">
                        @*<div class="blog_img">
                                <img src="~/img/blog-grid/masonry_02.jpg" alt="">
                            </div>*@
                        <div class="blog_content">
                            <div class="entry_post_info">
                                <a href="#">@item.IssueState</a>
                                <a href="#">@item.CreatedDate</a>
                            </div>
                            <a asp-controller="Issue" asp-action="UpdateIssue" asp-route-id="@item.Id">
                                <h5 class="f_p f_size_20 f_500 t_color mb_20">@item.IssueName</h5>
                            </a>
                            <p class="f_400 mb-0">
                                @item.Description
                            </p>
                            <br />
                            <div>
                                <button class="btn btn-success">
                                    <a asp-area="Admin" asp-controller="Technician" asp-action="IssueDetail" asp-route-id="@item.Id">
                                        DETAY
                                    </a>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

EvoComputerTechService/Areas/Admin/Views/Technician/CompletedIssuesDone.cshtml
@model List<Issue>


@{
    ViewBag.Title = "Tamamlanan Arızalar";
}

<section class="blog_area sec_pad">
    <div class="container">
        <div class="row" id="blog_masonry">
            @foreach (var item in Model)
            {
                <div class="col-lg-4 col-sm-6">
                    <div class="blog_grid_item mb-30">
                        @*<div class="blog_img">
                            <img src="~/img/blog-grid/masonry_02.jpg" alt="">
                            </div>*@
                        <div class="blog_content">
                            <div class="entry_post_info">
                                <a href="#">@item.IssueState</a>
                                <a href="#">@item.CreatedDate</a>
                            </div>
                            <a asp-controller="Issue" asp-action="UpdateIssue" asp-route-id="@item.Id">
                                <h5 class="f_p f_size_20 f_500 t_color mb_20">@item.IssueName</h5>
                            </a>
                            <p class="f_400 mb-0">
                                @item.Description
                            </p>
                            <br />
                            <div>
                                <button class="btn btn-success">
                                    <a asp-area="Admin" asp-controller="Technician" asp-action="IssueDetail" asp-route-id="@item.Id">
                                        DETAY
                                    </a>
                                </button>
                            </div>

                        </div>
                    </div>
                </div>
            }
        </div>

        <div>
            <button class="btn btn-success">
                <a asp-area="Admin" asp-controller="Technician" asp-action="MyIssues">
                    BACK TO MY ISSUES
                </a>
            </button>
        </div>
    </div>
</section>

EvoComputerTechService/Areas/Admin/Views/Technician/IssueDetail.cshtml
@model IssueProductViewModel
@{
    decimal toplam = 0m;

}
<div class="col-md-12">
    <div class="row">
        @foreach (var item in Model.Products)
        {
            <div class="col-md-3 layout-spacing">
                <div class="statbox widget box box-shadow">
                    <div class="widget-content widget-content-area px-0 py-0 product-cat10">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="card">
                                    <div class="wrapper">
                                        <div class="card-content-container text-center">
                                            <div class="content">
                                                button                                        <form asp-controller="Technician" asp-action="AddProduct" method="post" asp-route-id="@item.Id">

                                                    <button class="btn btn-default mb-3">
                                                        Urun Ekle
                                                    </button>

                                                </form>

                                                <h5 class="card-pricing">@item.Price</h5>
                                                <h1 class="title"><a href="#">@item.ProductName</a></h1>
                                                <p class="card-text">
                                                    @item.ProductDescription
                                                </p>
                                                <div class="row">
                                                    <div class="col-sm-6 col-6">
                                                        <p class="wishlist float-right">
                                                            <i class="flaticon-heart-1"></i>
                                                        </p>
                                                    </div>
                                                    <div class="col-sm-6 col-6">
                                                        <p class="zoom float-left">
                                                            <i class="flaticon-attachment"></i>
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>

                    </div>
                </div>
            </div>

        }
    </div>
</div>

<section class="checkout_area bg_color sec_pad">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="cart_total_box" style="width:900px">
                    <div class="card-body">
                    <h3 class="checkout_title f_p f_600 f_size_20 mb_20">
                        Products & Order Table
                    </h3>
                    <div id="order_review" class="woocommerce-checkout-review-order">
                        <table class="shop_table woocommerce-checkout-review-order-table">
                            <thead >
                                <tr>
                                    <th>ProductName</th>
                                    <th>Product Description</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    @*   <th></th>*@
                                </tr>
                            </thead>
                            @foreach (var item in Model.IssueProducts)
                            {
                                <tbody>
                                    <tr class="order_item">
                                        <td class="price">@item.Product.ProductName</td>
                                        <td class="price">@item.Product.ProductDescription</td>
                                        <td class="price">@item.Product.Price</td>
                                        <td class="price">@item.Quantity</td>
                                        @if ((int)item.Issue.IssueState < 3)
                                        {
                                            <form asp-controller="Technician" asp-action="DeleteProduct" method="post" asp-route-id="@item.ProductId">

                                            <td class="price">
                                                <button class=" mb-3">
                                                    Delete Product
                                                </button>
                                            </td>
                                            </form>
                                        }

                                        @{
                                            toplam += @item.Price;
                                        }
                                    </tr>

                                </tbody>
                            }

                            <tr class="subtotal order">
                                <td class="price">Order totals</td>
                                <td class="total">@toplam</td>
                            </tr>
                        </table>
                    </div>
                    <div class="condition">


                         @if ((int)TempData["buttonCheck"] <3)
                            {
                        <p>
                            Your personal data will be used to process your order, support your experience
                            throughout this website, and for other purposes described in our privacy policy.
                        </p>
                        <input type="checkbox" value="None" id="squarednine" name="check">
                        <label class="l_text" for="squarednine">
                            I have read and agree to the website terms
                            and conditions <span>*</span>
                        </label>
                      @*  <div class="row"> *@
                          <div class="d-flex justify-content-end">
                         <button type="submit" class="button bg-info text-light ">
                            <a asp-controller="Technician" asp-action="CompletedIssues" method="get">  Complete Issue  </a>
                        </button>
                        </div>
                   @*     </div>*@
                         }
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>

    </div>
</section>

@section Scripts
 {
<style>
    tr {
        padding: 0 30px 20px 0px
    }

    th {
        padding: 0 30px 20px 0px
    }

    td {
        padding: 0 30px 20px 0px
    }

        td > button {
            color: red
        }

            td > button:hover {
                color: blue;
                background: yellow
            }

</style>
 }

EvoComputerTechService/Areas/Admin/Views/Technician/MyIssues.cshtml
@model List<Issue>

@{
    ViewBag.Title = "Atanan Arızalar";
}

<section class="blog_area sec_pad">
    <div class="container">
        <div class="row" id="blog_masonry">
            @foreach (var item in Model)
            {
                <div class="col-lg-4 col-sm-6">
                    <div class="blog_grid_item mb-30">
                        @*<div class="blog_img">
                                <img src="~/img/blog-grid/masonry_02.jpg" alt="">
                            </div>*@
                        <div class="blog_content">
                            <div class="entry_post_info">
                                <a href="#">@item.IssueState</a>
                                <a href="#">@item.CreatedDate</a>
                            </div>
                            <a asp-controller="Issue" asp-action="UpdateIssue" asp-route-id="@item.Id">
                                <h5 class="f_p f_size_20 f_500 t_color mb_20">@item.IssueName</h5>
                            </a>
                            <p class="f_400 mb-0">
                                @item.Description
                            </p>
                            <br />
                            <div>
                                <button class="btn btn-success">
                                    <a asp-area="Admin" asp-controller="Technician" asp-action="AcceptIssue" asp-route-id="@item.Id">
                                        KABUL ET
                                    </a>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>